export const data = [
  {
    id: 1,
    nome: "Lion",
    imageUrl: "../assets/images/pet01.png",
    idade: "2 anos",
    especie: "Golden Retrivier",
    desc: "Vacinado",
  },
  {
    id: 2,
    nome: "Lucky",
    imageUrl: "../assets/images/pet02.png",
    idade: "3 anos",
    especie: "Vira lata",
    desc: "Vacinado",
  },
  {
    id: 3,
    nome: "Amora",
    imageUrl: "../assets/images/pet03.png",
    idade: "4 anos",
    especie: "Pastor Alemão",
    desc: "Vacinado",
  },
  {
    id: 4,
    nome: "Buddy",
    imageUrl: "../assets/images/pet04.png",
    idade: "5 anos",
    especie: "Labrador",
    desc: "Vacinado",
  },
  {
    id: 5,
    nome: "Cody",
    imageUrl: "../assets/images/pet05.png",
    idade: "6 anos",
    especie: "Vira lata",
    desc: "Vacinado",
  },
  {
    id: 6,
    nome: "Algodão",
    imageUrl: "../assets/images/pet06.png",
    idade: "2 anos",
    especie: "Siames",
    desc: "Vacinado",
  }
]